### ISSUE TITLE
Revise CSS

### ISSUE THREAD

**Issue by doduongthaituan** [huuthiet/FirstWeb#2]
Revise CSS:
- How to use CSS in HTML
- Box model
- Flexbox, grid
- Transition
- Animation
- Responsive
- layouts
- variables
- pseudo-class,
- pseudo-element
- ...

**Comment by huuthiet** [comment]
> * How to use CSS in HTML
There are 3 ways:
- Inline: use in tag by style=" " attribute 
- Internal: use in file HTML by tag style
- External: use a CSS file and link to HTML file
> * Box model
Include:
- content
- padding
- border
- margin
> * Flexbox, grid
1. Flexbox:
- Use for layout
2. Grid
- It divides the website page into columns and rows system, create a grid 
> * Transition
Loading...
> * Animation
Loading...
> * Responsive
Loading...
> * layouts
Loading...
> * variables
Loading...
> * pseudo-class,
Loading...
> * pseudo-element
Loading...
> * ...

**Comment by doduongthaituan** [comment]
https://github.com/huuthiet/FirstWeb/issues/2#issuecomment-1637119591 How to use flex, grid? example?

**Comment by huuthiet** [comment]
> [#2 (comment)](https://github.com/huuthiet/FirstWeb/issues/2#issuecomment-1637119591) How to use flex, grid? example?

**Comment by huuthiet** [comment]
> [#2 (comment)](https://github.com/huuthiet/FirstWeb/issues/2#issuecomment-1637119591) How to use flex, grid? example?

Use flex:
- The parent element has property: 
display: flex
With the parent element has properties:
flex-direction: select the main axis is row or column (default: row)
flex-wrap: allow elements can wrap or no-wrap (default: no-wrap) when line is full, it can set up the wrap direction (go up or go down (default))
justify-content: align the child elements by main axis
align-content: align the child elements by assist axis
- The child element has property:
flex: it's shorthand of flex-grow, flex-shrink, flex-basics
justify-self: same the justify-content but it only write at child elements
align-self: same above
order: set up the order of elements
